---
- name: restart_zookeeper
  shell: docker stop zookeeper ; docker rm zookeeper; docker run -v /app/zookeeper/data:/data -v /app/zookeeper/logs:/data/log -v /app/zookeeper/conf:/conf --name zookeeper  -p 2181:2181 -p 2888:2888 -p 3888:3888 -d zookeeper:3.6.1
